/* Magnitude Analysis helps us compare the measre values
  by categories .it helps us understand the importance of different categories .  
  
*/



-- Find total customers by countries

Select count(DISTINCT customer_id) total_customers , country From gold.dim_customers GROUP BY country ORDER BY	total_customers DESC

-- Find total customers by gender 

Select count(DISTINCT customer_id) total_customers , gender From gold.dim_customers GROUP BY gender  ORDER BY	total_customers DESC

-- Find Total products by category 

Select count(product_key) total_products , category FROM gold.dim_products GROUP BY category ORDER BY total_products DESC

-- what is the average costs in each category ?

Select category , avg(cost) average_cost FROM gold.dim_products GROUP BY category ORDER BY average_cost DESC

-- what is the total revenue generated for each category ?

Select p.category , sum(s.sales_amount) total_revenue from  gold.fact_sales as s   
LEFT JOIN gold.dim_products as p  on p.product_key = s.product_key 
GROUP BY p.category 

-- Find total revenue is generated by each customer 
SELECT c.customer_key ,
c.first_name ,
c.last_name ,
sum(s.sales_amount) total_revenue
FROM gold.fact_sales as s  
LEFT JOIN gold.dim_customers as c
on c.customer_key = s.customer_key
GROUP BY c.customer_key , c.first_name , c.last_name
ORDER BY total_revenue DESC



-- What is the distribution of sold items across countries ?
SELECT c.country , sum(s.quantity) items_sold FROM gold.fact_sales as s
LEFT JOIN gold.dim_customers as c on c.customer_key = s.customer_key GROUP BY c.country ORDER BY items_sold DESC


